package com.example.dao;

import com.example.entity.countrylanguage;
import com.example.entity.countrylanguageKey;

public interface countrylanguageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(countrylanguageKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated
     */
    int insert(countrylanguage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated
     */
    int insertSelective(countrylanguage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated
     */
    countrylanguage selectByPrimaryKey(countrylanguageKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(countrylanguage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(countrylanguage record);
}